services:
  telegram-bot:
    build: .
    container_name: rdmotors_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./database/rdmotors.db:/app/database/rdmotors.db
    command: python main.py
